version: '3.8'


services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - '5001:5001'
    volumes:
      - /app/node_modules
      - ./backend:/app


  client:
    stdin_open: true
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
