version: '3.8'

services:
  db:
    hostname: neo4j
    build:
      dockerfile: Dockerfile
      context: "./db"
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./db:/app
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
    healthcheck:
      test:  wget -O/dev/null -q http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 50
      start_period: 3s

  api:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  client:
    stdin_open: true
    ports:
      - '3000:3000'
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
